<a href="https://colab.research.google.com/github/keirabasma/Formation-IA/blob/main/workshop_3_chelghoum_AAPL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
from google.colab import files
files.upload()

Saving cars (1).csv to cars (1) (4).csv

{'cars (1) (4).csv': b',car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price\r\n0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.7,796,46.3,5,120000\r\n1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.9,1197,82,5,550000\r\n2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17,1197,80,5,215000\r\n3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.1,5,226000\r\n4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000\r\n5,Maruti Wagon R,Maruti,Wagon R,8,35000,Individual,Petrol,Manual,18.9,998,67.1,5,350000\r\n6,Hyundai i10,Hyundai,i10,8,40000,Dealer,Petrol,Manual,20.36,1197,78.9,5,315000\r\n7,Maruti Wagon R,Maruti,Wagon R,3,17512,Dealer,Petrol,Manual,20.51,998,67.04,5,410000\r\n8,Hyundai Venue,Hyundai,Venue,2,20000,Individual,Petrol,Automatic,18.15,998,118.35,5,1050000\r\n12,Maruti Swift,Maruti,Swift,4,28321,Dealer,Petrol,Manual,16.6,1197,85,5,511000\r\n14,Hyundai Verna,Hyundai,Verna,8,65278,Dealer,Diesel,Manual,22.32,1582,126.32,5,425000\r\n15,Renault Duster,Renault,Duster,5,50000,Individual,Diesel,Manual,19.64,1461,108.45,5,750000\r\n16,Mini Cooper,Mini,Cooper,4,6000,Dealer,Petrol,Automatic,14.41,1998,189.08,5,3250000\r\n17,Maruti Ciaz,Maruti,Ciaz,5,76000,Dealer,Diesel,Manual,28.09,1248,88.5,5,650000\r\n18,Maruti Swift,Maruti,Swift,5,20000,Individual,Diesel,Manual,25.2,1248,74,5,627000\r\n19,Mercedes-Benz C-Class,Mercedes-Benz,C-Class,7,65000,Dealer,Diesel,Automatic,19.27,2143,170,5,1425000\r\n20,Maruti Swift,Maruti,Swift,7,62200,Dealer,Diesel,Manual,28.4,1248,74,5,425000\r\n21,Toyota Innova,Toyota,Innova,8,110000,Individual,Diesel,Manual,12.99,2494,100.6,8,605000\r\n22,Maruti Baleno,Maruti,Baleno,6,20000,Individual,Petrol,Manual,21.4,1197,83.1,5,600000\r\n23,Maruti Swift Dzire,Maruti,Swift Dzire,5,40000,Individual,Petrol,Manual,20.85,1197,83.14,5,575000\r\n25,Volkswagen Vento,Volkswagen,Vento,8,47000,Dealer,Petrol,Manual,16.09,1598,103.2,5,425000\r\n26,Maruti Alto,Maruti,Alto,8,25000,Dealer,Petrol,Manual,20.92,998,67.1,5,230000\r\n27,Hyundai Creta,Hyundai,Creta,2,15000,Individual,Diesel,Manual,19.67,1582,126.2,5,1225000\r\n29,Honda City,Honda,City,6,50000,Individual,Petrol,Manual,17.4,1497,117.3,5,750000\r\n30,Mahindra Bolero,Mahindra,Bolero,10,25000,Individual,Diesel,Manual,13.6,2523,63,7,350000\r\n31,Maruti Swift Dzire,Maruti,Swift Dzire,6,90000,Individual,Diesel,Manual,26.59,1248,74,5,600000\r\n32,Maruti Swift Dzire,Maruti,Swift Dzire,8,45000,Dealer,Diesel,Manual,26.59,1248,74,5,390000\r\n33,Honda City,Honda,City,14,77253,Dealer,Petrol,Manual,17.7,1497,78,5,145000\r\n34,Hyundai i20,Hyundai,i20,3,25000,Individual,Petrol,Manual,17.19,1197,81.86,5,700000\r\n35,Toyota Fortuner,Toyota,Fortuner,8,110000,Individual,Diesel,Manual,13,2982,168.5,7,1150000\r\n36,Renault KWID,Renault,KWID,4,30000,Individual,Petrol,Manual,23.01,999,67,5,340000\r\n37,Honda Amaze,Honda,Amaze,5,39993,Dealer,Petrol,Manual,18.6,1199,88.76,5,465000\r\n38,Hyundai Santro,Hyundai,Santro,12,80000,Individual,Petrol,Manual,17.92,1086,62.1,5,125000\r\n39,Mahindra XUV500,Mahindra,XUV500,9,185000,Individual,Diesel,Manual,15.1,2179,140,7,600000\r\n40,Maruti Swift Dzire,Maruti,Swift Dzire,8,90000,Individual,Diesel,Manual,23.4,1248,74,5,380000\r\n44,Hyundai i20,Hyundai,i20,3,15000,Individual,Diesel,Manual,22.54,1396,88.73,5,850000\r\n45,Hyundai i20,Hyundai,i20,3,40000,Individual,Petrol,Manual,18.6,1197,81.83,5,598000\r\n46,Honda City,Honda,City,6,31180,Dealer,Petrol,Automatic,18,1497,117.3,5,700000\r\n50,Maruti Swift Dzire,Maruti,Swift Dzire,7,56000,Dealer,Diesel,Manual,23.4,1248,74,5,410000\r\n53,Maruti Baleno,Maruti,Baleno,5,52427,Dealer,Petrol,Automatic,21.4,1197,83.1,5,590000\r\n54,Mahindra Bolero,Mahindra,Bolero,1,40000,Individual,Diesel,Manual,21,1498,74.96,7,850000\r\n56,Mahindra KUV100,Mahindra,KUV100,3,17000,Individual,Petrol,Manual,18.15,1198,82,5,550000\r\n58,Maruti Baleno,Maruti,Baleno,5,22000,Dealer,Petrol,Manual,15.4,1590,94,5,625000\r\n59,Maruti Swift Dzire,Maruti,Swift Dzire,5,54000,Individual,Petrol,Manual,20.85,1197,83.14,5,600000\r\n60,Maruti Wagon R,Maruti,Wagon R,2,10000,Individual,Petrol,Manual,20.51,998,67.04,5,445000\r\n61,Maruti Ignis,Maruti,Ignis,2,20000,Individual,Petrol,Manual,20.89,1197,81.8,5,530000\r\n63,Maruti Wagon R,Maruti,Wagon R,3,53237,Trustmark Dealer,CNG,Manual,26.6,998,58.16,5,410000\r\n64,Datsun RediGO,Datsun,RediGO,3,27263,Individual,Petrol,Manual,22.5,999,68,5,350000\r\n66,Hyundai Verna,Hyundai,Verna,7,110000,Individual,Diesel,Manual,22.32,1582,126.3,5,520000\r\n67,Hyundai i20,Hyundai,i20,5,70000,Individual,Diesel,Manual,22.54,1396,88.73,5,750000\r\n68,Maruti Swift Dzire,Maruti,Swift Dzire,4,70000,Individual,Diesel,Manual,26.59,1248,74,5,560000\r\n71,Hyundai i20,Hyundai,i20,2,39000,Dealer,Petrol,Manual,18.6,1197,81.83,5,655000\r\n72,Hyundai Santro,Hyundai,Santro,14,56000,Dealer,Petrol,Manual,17.8,1086,63,5,125000\r\n75,Hyundai i20,Hyundai,i20,3,34000,Individual,Petrol,Manual,18.6,1197,81.83,5,550000\r\n76,Mahindra Scorpio,Mahindra,Scorpio,4,50000,Individual,Diesel,Manual,15.4,1997,120,7,1150000\r\n77,Volkswagen Vento,Volkswagen,Vento,9,77400,Individual,Diesel,Manual,20.54,1598,103.6,5,500000\r\n78,Mahindra Marazzo,Mahindra,Marazzo,2,36000,Individual,Diesel,Manual,17.3,1497,121,7,990000\r\n79,Hyundai Verna,Hyundai,Verna,8,47876,Dealer,Diesel,Manual,25,1493,113.42,5,551000\r\n80,Mahindra XUV500,Mahindra,XUV500,3,21500,Individual,Diesel,Automatic,15.1,2179,152.87,7,1650000\r\n81,Hyundai Grand,Hyundai,Grand,6,75000,Dealer,Diesel,Manual,24,1120,70,5,350000\r\n82,Ford Aspire,Ford,Aspire,4,58000,Dealer,Petrol,Manual,18.16,1196,86.8,5,500000\r\n83,Maruti Swift Dzire,Maruti,Swift Dzire,3,30000,Individual,Petrol,Manual,21.21,1197,81.8,5,575000\r\n84,Hyundai Grand,Hyundai,Grand,3,50000,Individual,Diesel,Manual,24,1186,73.97,5,545000\r\n85,Ford Figo,Ford,Figo,4,19093,Trustmark Dealer,Petrol,Manual,18.16,1196,86.8,5,525000\r\n86,Honda Amaze,Honda,Amaze,7,50000,Individual,Petrol,Manual,18,1198,86.7,5,400000\r\n87,Maruti Wagon R,Maruti,Wagon R,15,37000,Dealer,Petrol,Manual,14,1061,64,5,155000\r\n89,Maruti Swift Dzire,Maruti,Swift Dzire,5,47000,Dealer,Diesel,Manual,26.59,1248,74,5,545000\r\n90,Honda City,Honda,City,8,70000,Individual,Petrol,Manual,16.8,1497,116.3,5,545000\r\n91,Renault KWID,Renault,KWID,5,25000,Individual,Petrol,Manual,25.17,799,53.3,5,240000\r\n92,Maruti Vitara,Maruti,Vitara,3,26000,Dealer,Diesel,Manual,24.3,1248,88.5,5,725000\r\n93,Ford Aspire,Ford,Aspire,4,30000,Individual,Petrol,Manual,18.16,1196,86.8,5,480000\r\n94,Hyundai i20,Hyundai,i20,8,15000,Individual,Petrol,Manual,18.5,1197,82.9,5,375000\r\n95,Maruti Swift,Maruti,Swift,10,160000,Individual,Diesel,Manual,17.8,1248,75,5,225000\r\n96,Tata Tiago,Tata,Tiago,4,32100,Individual,Petrol,Manual,23.84,1199,84,5,400000\r\n97,Hyundai i20,Hyundai,i20,5,22000,Dealer,Petrol,Manual,18.5,1197,82.9,5,550000\r\n98,Mahindra Scorpio,Mahindra,Scorpio,5,44000,Dealer,Diesel,Manual,15.4,2179,120,7,1050000\r\n99,Volkswagen Polo,Volkswagen,Polo,5,78000,Dealer,Petrol,Manual,18.78,1198,74,5,450000\r\n100,Mercedes-Benz C-Class,Mercedes-Benz,C-Class,9,74352,Dealer,Petrol,Automatic,11.74,1796,186,5,775000\r\n101,Maruti Wagon R,Maruti,Wagon R,7,37000,Individual,Petrol,Manual,20.51,998,67.04,5,350000\r\n102,Honda City,Honda,City,7,69000,Dealer,Diesel,Manual,25.1,1498,98.6,5,550000\r\n103,Kia Seltos,Kia,Seltos,2,12120,Individual,Petrol,Manual,16.8,1497,113.4,5,1080000\r\n104,Maruti Baleno,Maruti,Baleno,5,52000,Dealer,Petrol,Manual,21.01,1197,81.8,5,575000\r\n105,Toyota Innova,Toyota,Innova,5,120000,Individual,Diesel,Manual,12.99,2494,100.6,8,950000\r\n106,Maruti Alto,Maruti,Alto,8,55000,Individual,Petrol,Manual,22.74,796,47.3,5,230000\r\n107,Hyundai i20,Hyundai,i20,10,160000,Individual,Diesel,Manual,21.9,1396,90,5,270000\r\n109,Ford Figo,Ford,Figo,10,40000,Individual,Petrol,Manual,15.6,1196,70,5,130000\r\n110,Maruti Swift Dzire,Maruti,Swift Dzire,9,46000,Dealer,Petrol,Manual,19.1,1197,85.8,5,370000\r\n111,Maruti Baleno,Maruti,Baleno,4,25000,Dealer,Petrol,Manual,21.4,1197,83.1,5,570000\r\n113,Volkswagen Polo,Volkswagen,Polo,8,90000,Dealer,Diesel,Manual,22.07,1199,73.9,5,365000\r\n114,Hyundai i20,Hyundai,i20,9,49566,Dealer,Petrol,Manual,18.5,1197,82.85,5,280000\r\n115,Hyundai Verna,Hyundai,Verna,3,14000,Dealer,Diesel,Automatic,22,1582,126.2,5,1250000\r\n116,Hyundai i20,Hyundai,i20,5,11000,Dealer,Petrol,Manual,18.6,1197,81.83,5,590000\r\n117,Maruti Celerio,Maruti,Celerio,3,5000,Individual,Petrol,Automatic,23.1,998,67.04,5,475000\r\n118,Ford Ecosport,Ford,Ecosport,4,55000,Dealer,Diesel,Manual,23,1498,98.96,5,685000\r\n119,Hyundai Verna,Hyundai,Verna,9,65000,Dealer,Diesel,Automatic,19.08,1582,126.32,5,380000\r\n120,Renault KWID,Renault,KWID,3,22000,Individual,Petrol,Manual,23.01,999,67,5,330000\r\n121,Maruti Baleno,Maruti,Baleno,3,7671,Trustmark Dealer,Petrol,Manual,21.01,1197,81.8,5,650000\r\n122,Maruti Wagon R,Maruti,Wagon R,5,66000,Individual,Petrol,Manual,20.51,998,67.04,5,325000\r\n123,Maruti Swift Dzire,Maruti,Swift Dzire,3,45156,Dealer,Petrol,Automatic,21.21,1197,81.8,5,640000\r\n124,Hyundai Venue,Hyundai,Venue,2,25000,Individual,Petrol,Manual,18.27,998,118.35,5,949000\r\n126,Hyundai Verna,Hyundai,Verna,6,120000,Individual,Diesel,Manual,23.9,1582,126.2,5,660000\r\n127,Maruti Swift,Maruti,Swift,7,28000,Dealer,Petrol,Manual,16.1,1197,85,5,435000\r\n128,Hyundai i20,Hyundai,i20,8,55000,Dealer,Diesel,Manual,21.9,1396,88.76,5,385000\r\n130,Hyundai Verna,Hyundai,Verna,2,14000,Dealer,Diesel,Automatic,22,1582,126.2,5,1250000\r\n132,Maruti Wagon R,Maruti,Wagon R,12,98780,Dealer,Petrol,Manual,18.9,998,67.1,5,155000\r\n133,Maruti Swift,Maruti,Swift,6,58000,Dealer,Diesel,Manual,25.2,1248,74,5,415000\r\n134,Maruti Alto,Maruti,Alto,10,30000,Individual,Petrol,Manual,20.92,998,67.1,5,251000\r\n135,Mahindra Scorpio,Mahindra,Scorpio,5,46400,Dealer,Diesel,Manual,15.4,2179,120,7,1150000\r\n136,Hyundai i10,Hyundai,i10,7,32111,Trustmark Dealer,Petrol,Manual,19.81,1086,68.05,5,310000\r\n137,Datsun GO,Datsun,GO,6,35000,Individual,Petrol,Manual,19.44,1198,67,7,350000\r\n138,Mahindra Scorpio,Mahindra,Scorpio,4,30000,Dealer,Diesel,Manual,15.4,1997,120,7,1125000\r\n139,BMW 5,BMW,5,5,63000,Dealer,Diesel,Automatic,18.59,2993,261.49,5,2600000\r\n141,Datsun GO,Datsun,GO,3,10000,Individual,Petrol,Manual,20.62,1198,67,7,480000\r\n142,Maruti Swift Dzire,Maruti,Swift Dzire,4,25000,Individual,Diesel,Automatic,28.4,1248,74.02,5,850000\r\n143,Hyundai Creta,Hyundai,Creta,4,102000,Dealer,Diesel,Automatic,17.01,1582,126.2,5,1100000\r\n144,Maruti Swift,Maruti,Swift,3,35000,Dealer,Petrol,Manual,22,1197,81.8,5,575000\r\n145,Maruti Swift Dzire,Maruti,Swift Dzire,9,49948,Dealer,Petrol,Manual,17.5,1298,85.8,5,340000\r\n147,Ford Ecosport,Ford,Ecosport,3,55000,Individual,Diesel,Manual,23,1498,98.96,5,925000\r\n148,Hyundai Grand,Hyundai,Grand,6,36000,Dealer,Petrol,Manual,18.9,1197,82,5,400000\r\n150,Honda City,Honda,City,5,49625,Dealer,Petrol,Manual,17.8,1497,117.3,5,725000\r\n151,Maruti Swift Dzire,Maruti,Swift Dzire,7,35000,Individual,Diesel,Manual,23.4,1248,74,5,600000\r\n152,Mahindra Scorpio,Mahindra,Scorpio,8,95000,Individual,Diesel,Manual,12.05,2179,120,8,550000\r\n153,Ford Aspire,Ford,Aspire,4,36000,Dealer,Diesel,Manual,25.83,1498,99,5,585000\r\n154,Maruti Wagon R,Maruti,Wagon R,2,50000,Individual,Petrol,Manual,21.79,998,67.05,5,411000\r\n155,Maruti Swift Dzire,Maruti,Swift Dzire,6,26500,Individual,Petrol,Manual,20.85,1197,83.14,5,450000\r\n156,Honda CR-V,Honda,CR-V,6,80000,Dealer,Petrol,Automatic,13.7,1997,153.86,5,1290000\r\n157,Volkswagen Polo,Volkswagen,Polo,6,46000,Dealer,Petrol,Manual,16.47,1198,74,5,455000\r\n158,Hyundai Grand,Hyundai,Grand,2,9000,Individual,Petrol,Manual,20.7,1197,81.86,5,710000\r\n161,Honda City,Honda,City,5,53000,Dealer,Petrol,Manual,16.8,1497,116.3,5,770000\r\n164,Ford Endeavour,Ford,Endeavour,3,11387,Individual,Diesel,Automatic,10.91,3198,197,7,2900000\r\n165,Honda Amaze,Honda,Amaze,3,50000,Individual,Diesel,Manual,25.8,1498,98.6,5,720000\r\n166,Mahindra KUV,Mahindra,KUV,5,52000,Dealer,Diesel,Manual,25.32,1198,77,5,375000\r\n168,Datsun GO,Datsun,GO,6,35000,Individual,Petrol,Manual,19.44,1198,67,7,400000\r\n169,Renault Duster,Renault,Duster,6,48000,Individual,Diesel,Manual,19.87,1461,83.8,5,600000\r\n170,Honda Jazz,Honda,Jazz,3,18000,Individual,Petrol,Manual,18.7,1199,88.7,5,600000\r\n171,Maruti Wagon R,Maruti,Wagon R,9,57413,Individual,LPG,Manual,14.4,998,61.7,5,270000\r\n172,Hyundai i20,Hyundai,i20,6,30000,Individual,Petrol,Manual,18.6,1197,81.83,5,500000\r\n173,Hyundai Verna,Hyundai,Verna,6,55000,Dealer,Diesel,Manual,23.9,1582,126.2,5,650000\r\n176,Maruti Swift,Maruti,Swift,3,10000,Individual,Petrol,Automatic,21.21,1197,81.8,5,660000\r\n178,BMW 3,BMW,3,5,68000,Dealer,Diesel,Automatic,22.69,1995,190,5,2090000\r\n180,Kia Seltos,Kia,Seltos,1,8000,Dealer,Petrol,Manual,16.8,1497,113.4,5,1275000\r\n182,Maruti Swift,Maruti,Swift,6,65000,Dealer,Diesel,Manual,28.4,1248,74,5,495000\r\n186,Hyundai Grand,Hyundai,Grand,5,25000,Individual,Petrol,Manual,18.9,1197,82,5,475000\r\n189,Maruti Ciaz,Maruti,Ciaz,6,70000,Individual,Petrol,Manual,20.73,1373,91.1,5,530000\r\n190,Tata Tiago,Tata,Tiago,5,9500,Individual,Petrol,Manual,23.84,1199,84,5,530000\r\n191,Hyundai Verna,Hyundai,Verna,6,9100,Individual,Petrol,Manual,17.01,1591,121.3,5,650000\r\n193,Honda City,Honda,City,11,86000,Dealer,Petrol,Manual,17,1497,118,5,335000\r\n195,Audi A4,Audi,A4,8,78000,Dealer,Diesel,Automatic,16.55,1968,147.51,5,1290000\r\n196,Ford Figo,Ford,Figo,10,60000,Individual,Diesel,Manual,20,1399,68,5,300000\r\n197,Maruti Wagon R,Maruti,Wagon R,2,7883,Trustmark Dealer,Petrol,Automatic,21.5,1197,81.8,5,550000\r\n198,Maruti Swift Dzire,Maruti,Swift Dzire,8,50205,Trustmark Dealer,Diesel,Manual,23.4,1248,74,5,390000\r\n199,Mahindra Bolero,Mahindra,Bolero,13,220000,Individual,Diesel,Manual,13.6,2523,63,7,260000\r\n200,Tata Tigor,Tata,Tigor,4,58000,Dealer,Diesel,Manual,24.7,1047,69,5,395000\r\n201,Mahindra Scorpio,Mahindra,Scorpio,9,170000,Individual,Diesel,Manual,12.05,2179,120,8,550000\r\n202,Maruti Swift Dzire,Maruti,Swift Dzire,3,15000,Individual,Petrol,Manual,22,1197,81.8,5,650000\r\n203,Maruti Swift,Maruti,Swift,5,71245,Dealer,Diesel,Manual,28.4,1248,74,5,375000\r\n207,Kia Seltos,Kia,Seltos,2,7000,Individual,Petrol,Manual,16.1,1353,138,5,1300000\r\n208,Maruti Alto,Maruti,Alto,3,20000,Individual,Petrol,Manual,23.95,998,67.05,5,360000\r\n209,Maruti Celerio,Maruti,Celerio,1,8700,Individual,Petrol,Manual,21.63,998,67.04,5,505000\r\n210,Maruti Alto,Maruti,Alto,2,25000,Individual,Petrol,Manual,24.7,796,47.3,5,310000\r\n211,Hyundai i20,Hyundai,i20,6,42000,Dealer,Petrol,Manual,18.6,1197,81.86,5,545000\r\n214,Mahindra Bolero,Mahindra,Bolero,15,120000,Individual,Diesel,Manual,13.6,2523,63,7,150000\r\n215,Maruti Baleno,Maruti,Baleno,3,50000,Individual,Petrol,Manual,21.4,1197,83.1,5,580000\r\n216,Maruti Wagon R,Maruti,Wagon R,10,58000,Individual,Petrol,Manual,18.9,998,67.1,5,250000\r\n217,Hyundai Verna,Hyundai,Verna,4,36000,Individual,Petrol,Manual,17.43,1396,105.5,5,650000\r\n220,Maruti Ertiga,Maruti,Ertiga,3,30000,Individual,Diesel,Manual,25.47,1248,88.5,7,410000\r\n221,Ford Ecosport,Ford,Ecosport,6,162828,Dealer,Diesel,Manual,22.77,1498,98.59,5,531000\r\n222,Ford Ecosport,Ford,Ecosport,3,7500,Individual,Diesel,Manual,23,1498,98.96,5,890000\r\n223,Tata Safari,Tata,Safari,5,47227,Dealer,Diesel,Manual,14,2179,138.1,7,775000\r\n224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998,67.04,5,435000\r\n225,Ford Figo,Ford,Figo,9,74000,Dealer,Diesel,Manual,20,1399,68.05,5,185000\r\n226,Mahindra Bolero,Mahindra,Bolero,10,47000,Dealer,Diesel,Manual,15.96,2523,62.1,7,440000\r\n227,Hyundai i20,Hyundai,i20,6,50000,Individual,Petrol,Manual,18.6,1197,81.83,5,450000\r\n228,Maruti Baleno,Maruti,Baleno,4,100000,Individual,Petrol,Manual,21.4,1197,83.1,5,600000\r\n229,Maruti Celerio,Maruti,Celerio,7,35000,Individual,Petrol,Manual,23.1,998,67.04,5,320000\r\n230,Hyundai i20,Hyundai,i20,5,50000,Individual,Diesel,Manual,21.19,1396,88.73,5,700000\r\n231,Ford Aspire,Ford,Aspire,3,10000,Individual,Petrol,Manual,18.16,1196,86.8,5,630000\r\n232,Maruti Alto,Maruti,Alto,5,10370,Individual,Petrol,Manual,22.74,796,47.3,5,320000\r\n233,Honda City,Honda,City,8,62000,Dealer,Petrol,Manual,16.8,1497,116.3,5,465000\r\n236,Hyundai i20,Hyundai,i20,5,40000,Individual,Petrol,Manual,18.6,1197,81.83,5,550000\r\n237,Maruti Swift,Maruti,Swift,4,60000,Individual,Petrol,Manual,22,1197,81.8,5,445000\r\n238,Tata Safari,Tata,Safari,8,67231,Dealer,Diesel,Manual,14,2179,138.1,7,705000\r\n239,Maruti Wagon R,Maruti,Wagon R,8,64000,Dealer,CNG,Manual,33.54,998,67.04,5,270000\r\n241,Honda City,Honda,City,7,63000,Dealer,Diesel,Manual,26,1498,98.6,5,475000\r\n242,Toyota Fortuner,Toyota,Fortuner,6,80000,Individual,Diesel,Manual,12.55,2982,168.5,7,1755000\r\n243,Honda City,Honda,City,10,55000,Dealer,Petrol,Manual,16.9,1497,100,5,350000\r\n244,Hyundai i20,Hyundai,i20,5,11000,Dealer,Petrol,Manual,18.6,1197,81.83,5,575000\r\n246,Renault KWID,Renault,KWID,4,17000,Individual,Petrol,Manual,23.01,999,67,5,360000\r\n247,Maruti Alto,Maruti,Alto,4,25000,Individual,Petrol,Manual,24.7,796,47.3,5,275000\r\n248,Datsun GO,Datsun,GO,5,33350,Individual,Petrol,Manual,19.44,1198,67,7,320000\r\n250,Hyundai Grand,Hyundai,Grand,6,62000,Dealer,Petrol,Manual,18.9,1197,82,5,370000\r\n252,Maruti Swift Dzire,Maruti,Swift Dzire,12,59000,Individual,Petrol,Manual,17.5,1298,85.8,5,275000\r\n254,Honda City,Honda,City,7,86113,Dealer,Petrol,Manual,17.4,1497,117.3,5,550000\r\n256,Maruti Swift Dzire,Maruti,Swift Dzire,3,10000,Individual,Diesel,Manual,28.4,1248,74.02,5,750000\r\n258,Maruti Wagon R,Maruti,Wagon R,6,92537,Individual,Petrol,Manual,20.51,998,67.04,5,272000\r\n259,Maruti Ciaz,Maruti,Ciaz,2,27645,Dealer,Diesel,Manual,28.09,1248,88.5,5,951000\r\n260,Maruti Alto,Maruti,Alto,8,46242,Individual,Petrol,Manual,20.92,998,67.1,5,280000\r\n261,Honda City,Honda,City,8,70000,Individual,Petrol,Manual,16.8,1497,116.3,5,545000\r\n262,Renault KWID,Renault,KWID,1,6000,Individual,Petrol,Manual,22.3,799,53.26,5,450000\r\n263,Hyundai i20,Hyundai,i20,4,64000,Dealer,Petrol,Manual,18.6,1197,81.83,5,480000\r\n264,Mahindra Scorpio,Mahindra,Scorpio,4,93000,Dealer,Diesel,Manual,15.4,1997,120,7,1060000\r\n265,Maruti Alto,Maruti,Alto,8,26200,Dealer,Petrol,Manual,22.74,796,47.3,5,235000\r\n266,Maruti Baleno,Maruti,Baleno,4,25000,Individual,Petrol,Manual,21.4,1197,83.1,5,590000\r\n269,Toyota Fortuner,Toyota,Fortuner,3,50000,Dealer,Diesel,Automatic,12.9,2755,174.5,7,2950000\r\n270,Hyundai Santro,Hyundai,Santro,13,80000,Individual,Petrol,Manual,17.92,1086,62.1,5,110000\r\n271,Mahindra Scorpio,Mahindra,Scorpio,14,110000,Individual,Diesel,Manual,13.5,2179,115,5,280000\r\n272,Audi A4,Audi,A4,5,55000,Dealer,Petrol,Automatic,17.84,1395,147.51,5,1851000\r\n273,Honda City,Honda,City,3,25000,Individual,Petrol,Manual,17.4,1497,117.3,5,750000\r\n274,Hyundai Grand,Hyundai,Grand,6,36000,Dealer,Petrol,Manual,18.9,1197,81.86,5,400000\r\n275,Maruti Swift Dzire,Maruti,Swift Dzire,6,40000,Individual,Diesel,Manual,26.59,1248,74,5,530000\r\n276,Mahindra Thar,Mahindra,Thar,3,25000,Individual,Diesel,Manual,16.55,2498,105,6,870000\r\n277,Renault KWID,Renault,KWID,3,30038,Dealer,Petrol,Manual,25.17,799,53.3,5,295000\r\n278,Tata Tiago,Tata,Tiago,4,53000,Individual,Diesel,Manual,27.28,1047,69,5,370000\r\n279,Maruti Swift,Maruti,Swift,3,5000,Individual,Petrol,Manual,21.21,1197,81.8,5,530000\r\n281,Renault KWID,Renault,KWID,4,35000,Individual,Petrol,Automatic,24.04,999,67,5,350000\r\n282,Ford Ecosport,Ford,Ecosport,8,62000,Dealer,Diesel,Manual,22.7,1498,89.84,5,470000\r\n283,Ford Aspire,Ford,Aspire,6,42000,Individual,Diesel,Manual,25.83,1498,99,5,390000\r\n285,Mahindra Scorpio,Mahindra,Scorpio,6,80000,Individual,Diesel,Manual,15.4,2179,120,7,920000\r\n286,Mahindra XUV500,Mahindra,XUV500,8,60000,Individual,Diesel,Manual,15.1,2179,140,7,550000\r\n287,Hyundai Verna,Hyundai,Verna,7,45000,Individual,Diesel,Manual,22.32,1582,126.32,5,63500

In [10]:
df = pd.read_csv("cars (1).csv")
df.head()

   Unnamed: 0       car_name    brand     model  vehicle_age  km_driven seller_type fuel_type transmission_type  mileage  engine  max_power  seats   price
0           0    Maruti Alto   Maruti      Alto            9     120000  Individual    Petrol            Manual    19.70     796      46.30      5  120000
1           1  Hyundai Grand  Hyundai     Grand            5      20000  Individual    Petrol            Manual    18.90    1197      82.00      5  550000
2           2    Hyundai i20  Hyundai       i20           11      60000  Individual    Petrol            Manual    17.00    1197      80.00      5  215000
3           3    Maruti Alto   Maruti      Alto            9      37000  Individual    Petrol            Manual    20.92     998      67.10      5  226000
4           4  Ford Ecosport     Ford  Ecosport            6      30000      Dealer    Diesel            Manual    22.77    1498      98.59      5  570000

In [11]:
df.groupby("brand")["price"].mean()

brand
Audi             1.966865e+06
BMW              2.693827e+06
Bentley          9.266667e+06
Datsun           3.205176e+05
Ferrari          3.950000e+07
Force            7.000000e+05
Ford             6.452241e+05
Honda            6.177569e+05
Hyundai          5.761539e+05
ISUZU            1.897500e+06
Isuzu            1.355000e+06
Jaguar           2.643034e+06
Jeep             1.795805e+06
Kia              1.735250e+06
Land Rover       3.823902e+06
Lexus            5.146500e+06
MG               1.752947e+06
Mahindra         7.874550e+05
Maruti           4.870893e+05
Maserati         6.100000e+06
Mercedes-AMG     5.100000e+06
Mercedes-Benz    2.480742e+06
Mini             2.182647e+06
Nissan           9.553636e+05
Porsche          5.161190e+06
Renault          4.409851e+05
Rolls-Royce      2.420000e+07
Skoda            7.840898e+05
Tata             6.835349e+05
Toyota           1.371317e+06
Volkswagen       5.165468e+05
Volvo            3.729700e+06
Name: price, dtype: float64

In [12]:
df.groupby("fuel_type").size()

fuel_type
CNG          301
Diesel      7419
Electric       4
LPG           44
Petrol      7643
dtype: int64

In [13]:
df.groupby("brand")["mileage"].count()

brand
Audi              192
BMW               439
Bentley             3
Datsun            170
Ferrari             1
Force               1
Ford              790
Honda            1485
Hyundai          2982
ISUZU               2
Isuzu               8
Jaguar             59
Jeep               41
Kia                32
Land Rover         51
Lexus              10
MG                 19
Mahindra         1011
Maruti           4992
Maserati            2
Mercedes-AMG        1
Mercedes-Benz     337
Mini               17
Nissan             11
Porsche            21
Renault           536
Rolls-Royce         1
Skoda             334
Tata              430
Toyota            793
Volkswagen        620
Volvo              20
Name: mileage, dtype: int64

In [14]:
df.groupby("fuel_type")["price"].agg(["mean", "min", "max"])

                   mean      min       max
fuel_type
CNG        4.176877e+05   125000   1080000
Diesel     1.000469e+06   100000   9200000
Electric   1.853500e+06  1699000   2000000
LPG        2.062727e+05    80000    420000
Petrol     5.728619e+05    40000  39500000

In [15]:
df.groupby("transmission_type").agg({
    "price": "mean",
    "km_driven": "mean",
    "mileage": "mean"
})

                          price     km_driven    mileage
transmission_type
Automatic          1.579557e+06  48184.767106  17.391008
Manual             5.652852e+05  57553.285481  20.303206

In [16]:
pd.pivot_table(
    df,
    values="price",
    index="brand",
    columns="fuel_type",
    aggfunc="mean"
)

fuel_type                CNG        Diesel   Electric            LPG        Petrol
brand
Audi                     NaN  1.951424e+06        NaN            NaN  2.086182e+06
BMW                      NaN  2.715868e+06        NaN            NaN  2.495955e+06
Bentley                  NaN           NaN        NaN            NaN  9.266667e+06
Datsun                   NaN           NaN        NaN            NaN  3.205176e+05
Ferrari                  NaN           NaN        NaN            NaN  3.950000e+07
Force                    NaN  7.000000e+05        NaN            NaN           NaN
Ford                     NaN  6.785722e+05        NaN            NaN  5.731920e+05
Honda          422000.000000  6.191512e+05        NaN            NaN  6.175078e+05
Hyundai        435416.666667  6.946809e+05        NaN  247769.230769  5.134466e+05
ISUZU                    NaN  1.897500e+06        NaN            NaN           NaN
Isuzu                    NaN  1.355000e+06        NaN            NaN           NaN
Jaguar                   NaN  2.594446e+06        NaN            NaN  3.550000e+06
Jeep                     NaN  1.666731e+06        NaN            NaN  2.019533e+06
Kia                      NaN  2.071357e+06        NaN            NaN  1.473833e+06
Land Rover               NaN  3.727688e+06        NaN            NaN  5.363333e+06
Lexus                    NaN           NaN        NaN            NaN  5.146500e+06
MG                       NaN  1.793429e+06        NaN            NaN  1.729333e+06
Mahindra       400000.000000  8.020753e+05        NaN            NaN  5.357963e+05
Maruti         414771.126761  6.144817e+05        NaN  188870.967742  4.244746e+05
Maserati                 NaN  6.100000e+06        NaN            NaN           NaN
Mercedes-AMG             NaN           NaN        NaN            NaN  5.100000e+06
Mercedes-Benz            NaN  2.489936e+06        NaN            NaN  2.454727e+06
Mini                     NaN  1.866429e+06        NaN            NaN  2.404000e+06
Nissan                   NaN  9.698571e+05        NaN            NaN  9.300000e+05
Porsche                  NaN  4.781000e+06        NaN            NaN  6.111667e+06
Renault                  NaN  5.569234e+05        NaN            NaN  3.668838e+05
Rolls-Royce              NaN           NaN        NaN            NaN  2.420000e+07
Skoda                    NaN  7.650153e+05        NaN            NaN  8.111812e+05
Tata                     NaN  7.917804e+05        NaN            NaN  5.258057e+05
Toyota         730000.000000  1.371569e+06  1853500.0            NaN  1.360307e+06
Volkswagen               NaN  5.000651e+05        NaN            NaN  5.327125e+05
Volvo                    NaN  3.729700e+06        NaN            NaN           NaN

In [17]:
df.groupby("brand")["price"].mean().sort_values(ascending=False)

brand
Ferrari          3.950000e+07
Rolls-Royce      2.420000e+07
Bentley          9.266667e+06
Maserati         6.100000e+06
Porsche          5.161190e+06
Lexus            5.146500e+06
Mercedes-AMG     5.100000e+06
Land Rover       3.823902e+06
Volvo            3.729700e+06
BMW              2.693827e+06
Jaguar           2.643034e+06
Mercedes-Benz    2.480742e+06
Mini             2.182647e+06
Audi             1.966865e+06
ISUZU            1.897500e+06
Jeep             1.795805e+06
MG               1.752947e+06
Kia              1.735250e+06
Toyota           1.371317e+06
Isuzu            1.355000e+06
Nissan           9.553636e+05
Mahindra         7.874550e+05
Skoda            7.840898e+05
Force            7.000000e+05
Tata             6.835349e+05
Ford             6.452241e+05
Honda            6.177569e+05
Hyundai          5.761539e+05
Volkswagen       5.165468e+05
Maruti           4.870893e+05
Renault          4.409851e+05
Datsun           3.205176e+05
Name: price, dtype: float64